# Basic https://www.jekyll.com.cn/docs/configuration/
title: iOS/Mac Development Engineering
user: dgynfi
subtitle: Personal Website
description: dgynfi's blog
# 头像里面的标题
avatarTitle: dgynfi
# 头像里面的描述
avatarDesc: iOSre / Anti
url: "https://dgynfi.github.io"
mainEntityOfPage: "https://dgynfi.github.io/archive/"

# Comment
comment:
    disqus: iOS/Mac/Flutter/...
    # uyan: 2143225  # 有言id,登录有言官网申请
    gitment: yes

gitcomments:
    repo: githubpages-comments
    client_id: eb8baa6afd018fb78abf
    client_secret: c7b3a1a69585b929f76b9b849a5266c6198d8498


# Social
social:
    github: dgynfi
    mail: vinphy.teng@foxmail.com
    technical_exchange_group: 155353383.

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: e7f6d46714fcd28fb24be011203bee5f  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-111030597-1
    host: auto  

Params: 
    Search: 站内搜索

# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://dgynfi.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination 分页功能
plugins: [jekyll-paginate,jekyll-sitemap,jekyll-feed]
paginate: 20
paginate_path: "page/:num/"

